name: Build and deploy Python app to Azure Web App - HerbalChatRAG

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Python version
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "Poetry installed"

      # Install dependencies using Poetry
      - name: Install dependencies with Poetry
        run: |
          poetry install --no-dev  # Use --no-dev if you want to skip development dependencies

      # Optional: Run tests here
      # - name: Run Tests
      #   run: |
      #     poetry run pytest

      # Zip the artifact for deployment
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "venv/*" "venv" "venv/.env"

      # Upload the artifact to be deployed
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT
    steps:
      # Download the artifact
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Unzip the artifact
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5BF88D708845472E92E973DAE7EBFCB5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BCFD3B9D850B4A32A0E3004601BBE88D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E626940DE6A6413CBFB0BB6E0CAD54A9 }}

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'HerbalChatRAG'
          slot-name: 'Production'
